status = ["Rustfmt", "grcov", "stable-x86_64-pc-windows-msvc", "stable-x86_64-apple-darwin", "stable-x86_64-unknown-linux-gnu", "stable-x86_64-unknown-linux-musl", "beta-x86_64-pc-windows-msvc", "beta-x86_64-apple-darwin", "beta-x86_64-unknown-linux-gnu", "beta-x86_64-unknown-linux-musl"]
delete_merged_branches = true
